name: Deploy to EC2

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.91.67.160 << 'EOF'
            # Install uv if not present
            if ! command -v uv &> /dev/null; then
              echo "uv not found. Installing..."
              curl -LsSf https://astral.sh/uv/install.sh | sh
              export PATH="$HOME/.local/bin:$PATH"
            fi

            # Ensure uv is available in PATH
            export PATH="$HOME/.local/bin:$PATH"

            # Go to project directory (clone if needed)
            if [ ! -d "Taxi-Duration-Prediction" ]; then
              git clone https://github.com/AhmadHammad21/Taxi-Duration-Prediction.git
            fi
            cd Taxi-Duration-Prediction

            # Checkout dev branch
            git fetch origin
            git checkout dev
            git pull

            # Sync dependencies
            uv sync

            # Docker steps (with BuildKit enabled)
            export DOCKER_BUILDKIT=1
            export COMPOSE_DOCKER_CLI_BUILD=1
            sudo docker-compose pull
            sudo docker-compose up --build -d
          EOF